version: '3.8'

services:
  db:
    build: ./db
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: clasificacion_niza
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/clasificacion_niza.sql:/docker-entrypoint-initdb.d/clasificacion_niza.sql

  php:
    build: ./php
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
